config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :list_of_users, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "landing_page#index"
  # admin
  namespace :admin do
    get 'dashboard/index'
    root to: 'dashboard#index', as: 'dashboard'
    # users
    resources :users do
      member do
        patch :approve
        delete :deny
        # get 'chat'
      end
      # invite_user
      collection do
        get :invite_user_form
        post :invite_user
      end
    end
    resources :adoption_applications, only: [:index, :show]
    resources :adopters, only: [:edit, :update]
    resources :shelters, only: [:edit, :update]
    resources :pets, only: [:show]
  end

  devise_scope :user do
    get 'invite_user/:invitation_token', to: 'users/registrations#new_invited_user', as: 'new_invitation'
    post 'create_user', to: 'users/registrations#create_invited_user'
  end

  namespace :adopter do
    get 'dashboard', to: 'dashboard#index'
    resources :favorites, only: [:index, :create, :destroy]
    resources :pets, only: [:index, :show, :create] do
      resources :comments, only: [:create, :destroy]
    end
    resources :adoption_applications
  end

  namespace :shelter_namespace, path: 'shelter' do
    get 'dashboard', to: 'dashboard#index'
    resources :pets do
      member do
        patch :update_status
        delete :delete_photo  # Adding this line for the delete photo action
      end
      collection do
        post :uploads  # Adding this line for the uploads action in the create new pet view for shelters
      end
      resources :pet_comments, only: [:create]
    end
    resources :adoption_applications, only: [:index, :show, :edit, :update] do
      member do
        patch :approve
        patch :deny
        patch :pending
      end
    end
    resources :adopters, only: [:show]
    resources :chats, only: [:index, :show, :create]
  end

  namespace :sendbird do
    post '/create_group_channel_to_sendbird', to: 'sendbird#create_group_channel_to_sendbird'
    get 'list_users', to: 'sendbird#list_users'
    post 'send_message_to_sendbird', to: 'sendbird#send_message_to_sendbird'
    get 'fetch_messages_from_sendbird', to: 'sendbird#fetch_messages_from_sendbird'
  end

  # resources :list_of_users, only: [:index]
end

app/models/pet.rb
class Pet < ApplicationRecord
  geocoded_by :location
  after_validation :geocode

  enum adoption_status: { available: 0, pending: 1, adopted: 2 }

  belongs_to :shelter
  has_many :favorites
  has_many :favorited_by_users, through: :favorites, source: :use
  has_many :adoption_applications
  has_many :pet_comments

  validates :name, presence: true
  validates :species, presence: true
  validates :breed, presence: true

  has_many_attached :photos

  scope :filter_by_species, ->(species) { where(species: species) if species.present? }
  scope :filter_by_age, ->(age) { where(age: age) if age.present? }
  scope :filter_by_gender, ->(gender) { where(gender: gender) if gender.present? }
  scope :filter_by_temperament, ->(temperament) { where(temperament: temperament) if temperament.present? }
  scope :filter_by_location, ->(location, distance, unit) {
    if location.present?
      near(location, distance || 15, units: unit || :mi)
    else
      where.not(adoption_status: 'adopted')
    end
  }
  scope :species_counts, -> { group(:species).count }
  scope :age_counts, -> { group(:age).count }
  scope :gender_counts, -> { group(:gender).count }
  scope :temperament_counts, -> { group(:temperament).count }
end

app/controllers/admin/pets_controller.rb
module Admin
    class PetsController < BaseController
      def show
        @pet = Pet.find(params[:id])
      end
    end
  end
  

app/controllers/adopter/pets_controller.rb
class Adopter::PetsController < Adopter::BaseController

  def index
    @pets = Pet.filter_by_species(params[:species])
                .filter_by_age(params[:age])
                .filter_by_gender(params[:gender])
                .filter_by_temperament(params[:temperament])
                .filter_by_location(params[:location], params[:distance], params[:unit])
    @species_counts = Pet.species_counts
    @age_counts = Pet.age_counts
    @gender_counts = Pet.gender_counts
    @temperament_counts = Pet.temperament_counts
  end

  def show
    @pet = Pet.find(params[:id])
    @pet_comment = PetComment.new
  end

  def create
    pet = Pet.find(params[:pet_id])
    if current_user.favorites.include?(pet)
      current_user.favorites.delete(pet)
      flash[:notice] = "Removed from favorites"
    else
      current_user.favorites << pet
      flash[:notice] = "Added to favorites"
    end
    redirect_to pets_path
  end

end

app/controllers/shelter/pets_controller.rb
module Shelter
  class PetsController < BaseController
    before_action :set_pet, only: [:show, :edit, :update, :destroy, :update_status]

  def index
    @pets = current_user.shelter.pets

    if params[:location].present?
      distance = params[:distance].present? ? params[:distance].to_f : 15
      unit = params[:unit] == 'km' ? :km : :mi  # allows user to select if km or miles
      @pets = @pets.near(params[:location], distance, units: unit)
    end
  end


  def show
    @pet_comment = PetComment.new
  end



  def create
    @pet = current_user.shelter.pets.build(pet_params)
    if @pet.save
      flash[:notice] = "Pet added successfully"
      redirect_to shelter_pets_path
    else
      render :new
    end
  end



  def edit
  end

  def update
    if @pet.update(pet_params)
      flash[:notice] = "Pet updated successfully"
      redirect_to shelter_pet_path(@pet)
    else
      render :edit
    end
  end


  def destroy
    @pet.destroy
    flash[:notice] = "Pet removed successfully"
    redirect_to shelter_pets_path
  end

  def update_status
    if @pet.update(adoption_status: params[:adoption_status])
      flash[:notice] = "Pet status updated successfully"
    else
      flash[:alert] = "Unable to update status"
    end
    redirect_to shelter_pet_path(@pet)
  end

  def update_status
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :species, :breed, :age, :size, :gender, :temperament, :description, :photo_url, :location, :adoption_status)
   end
  end
end

app/controllers/shelter_namespace/adopters_controller.rb
module ShelterNamespace
  class AdoptersController < BaseController
      def show
          @adopter = Adopter.find(params[:id])
        end
      end
  end

app/controllers/shelter_namespace/adoption_applications_controller.rb
module ShelterNamespace
  class AdoptionApplicationsController < BaseController
    before_action :set_adoption_application, only: [:show, :update, :approve, :deny, :pending]

    def index
      @adoption_applications = current_user.shelter.adoption_applications
                                          .includes(:adopter, :pet)
                                          .joins(adopter: :user)
                                          .order('adoption_applications.created_at ASC')
    end

    def show
    end

    def update
      if @adoption_application.update(adoption_application_params)
        flash[:notice] = "Adoption application updated successfully"
        redirect_to shelter_namespace_adoption_application_path(@adoption_application)
      else
        render :edit
      end
    end

    def approve
      ActiveRecord::Base.transaction do
        @adoption_application.update!(status: :approved)
        update_pet_status(@adoption_application.pet)
        AdoptionApplicationMailer.application_approved(@adoption_application).deliver_later
      end
      flash[:notice] = "Adoption application approved. Email sent"
      redirect_to shelter_namespace_adoption_applications_path
    rescue ActiveRecord::RecordInvalid => e
      flash[:alert] = "Unable to approve adoption application: #{e.message}"
      redirect_to shelter_namespace_adoption_applications_path
    end

    def deny
      ActiveRecord::Base.transaction do
        @adoption_application.update!(status: :rejected)
        update_pet_status(@adoption_application.pet)
        AdoptionApplicationMailer.application_denied(@adoption_application).deliver_later
      end
      flash[:notice] = "Adoption application rejected. Email sent"
      redirect_to shelter_namespace_adoption_applications_path
    rescue ActiveRecord::RecordInvalid => e
      flash[:alert] = "Unable to reject adoption application: #{e.message}"
      redirect_to shelter_namespace_adoption_applications_path
    end

    def pending
      ActiveRecord::Base.transaction do
        @adoption_application.update!(status: :submitted)
        update_pet_status(@adoption_application.pet)
        AdoptionApplicationMailer.application_pending(@adoption_application).deliver_later
      end
      flash[:notice] = "Adoption application pending. Email sent"
      redirect_to shelter_namespace_adoption_applications_path
    rescue ActiveRecord::RecordInvalid => e
      flash[:alert] = "Unable to set adoption application to pending: #{e.message}"
      redirect_to shelter_namespace_adoption_applications_path
    end

    private

    def set_adoption_application
      @adoption_application = AdoptionApplication.find(params[:id])
    end

    def adoption_application_params
      params.require(:adoption_application).permit(:status, :adopter_id, :pet_id, :application_date)
    end

    def update_pet_status(pet)
      if pet.adoption_applications.approved.exists?
        pet.update!(adoption_status: :adopted)
      elsif pet.adoption_applications.submitted.exists?
        pet.update!(adoption_status: :pending)
      else
        pet.update!(adoption_status: :available)
      end
    end
  end
end

app/controllers/shelter_namespace/base_controller.rb
module ShelterNamespace
  class BaseController < ApplicationController
    before_action :authenticate_user!
    before_action :ensure_shelter

    private

    def ensure_shelter


      unless current_user&.shelter?
        redirect_to root_path, alert: 'Access denied.'
      end
    end
  end
end

app/controllers/shelter_namespace/dashboard_controller.rb
module ShelterNamespace
  class DashboardController < BaseController
  def index
    @total_pets = current_user.shelter.pets.count
    @adopted_pets = current_user.shelter.pets.adopted.count
    @pending_pets = current_user.shelter.pets.pending.count
    @available_pets = current_user.shelter.pets.available.count
  end
 end
end

app/controllers/shelter_namespace/pet_comments_controller.rb
module ShelterNamespace
  class PetCommentsController < BaseController
    before_action :set_pet

    def create
      @pet_comment = @pet.pet_comments.build(pet_comment_params)
      @pet_comment.user = current_user

      if @pet_comment.save
        flash[:notice] = "Comment added successfully"
        redirect_to shelter_namespace_pet_path(@pet)
      else
        @pet_comments = @pet.pet_comments
        flash.now[:alert] = "Unable to add comment"
        respond_to do |format|
          format.turbo_stream { render turbo_stream: turbo_stream.replace("pet_comments_section", partial: "shelter_namespace/pets/comments", locals: { pet: @pet, pet_comments: @pet_comments }) }
          format.html { render 'shelter_namespace/pets/show' }
        end
      end
    end

    private

    def set_pet
      @pet = Pet.find(params[:pet_id])
    end

    def pet_comment_params
      params.require(:pet_comment).permit(:comment_text)
    end
  end
end

app/controllers/shelter_namespace/pets_controller.rb
module ShelterNamespace
  class PetsController < BaseController
    before_action :set_pet, only: [:show, :edit, :update, :destroy, :update_status, :delete_photo]

    def index
      @pets = current_user.shelter.pets

      if params[:location].present?
        distance = params[:distance].present? ? params[:distance].to_f : 15
        unit = params[:unit] == 'km' ? :km : :mi  # allows user to select if km or miles
        @pets = @pets.near(params[:location], distance, units: unit)
      end
    end

    def show
      @pet_comments = @pet.pet_comments.includes(:user)
      @pet_comment = PetComment.new
    end

    def new
      @pet = Pet.new
    end

    def create
      @pet = current_user.shelter.pets.build(pet_params.except(:photo_urls))
      if @pet.save
        attach_photos if params[:pet][:photo_urls].present?
        flash[:notice] = "Pet added successfully"
        redirect_to shelter_namespace_pets_path
      else
        render :new
      end
    end  

    def edit
    end

    def update
      if @pet.update(pet_params.except(:photo_urls))
        attach_photos if params[:pet][:photo_urls].present?
        flash[:notice] = "Pet updated successfully"
        redirect_to shelter_namespace_pet_path(@pet)
      else
        render :edit
      end
    end

    def destroy
      @pet.destroy
      flash[:notice] = "Pet removed successfully"
      redirect_to shelter_namespace_pets_path
    end

    def update_status
      if @pet.update(adoption_status: params[:adoption_status])
        flash[:notice] = "Pet status updated successfully"
      else
        flash[:alert] = "Unable to update status"
      end
      redirect_to shelter_namespace_pet_path(@pet)
    end

    def uploads
      uploaded_file = params[:file]
      blob = ActiveStorage::Blob.create_and_upload!(
        io: uploaded_file,
        filename: uploaded_file.original_filename,
        content_type: uploaded_file.content_type
      )
      render json: { file_url: blob.signed_id }
    end

    def delete_photo
      photo = @pet.photos.find(params[:photo_id])
      photo.purge
      flash.now[:notice] = "Photo deleted successfully"
      
      respond_to do |format|
        format.html { redirect_to shelter_namespace_pet_path(@pet) }
        format.js
      end
    end  

    private

    def set_pet
      @pet = Pet.find(params[:id])
    end

    def pet_params
      params.require(:pet).permit(:name, :species, :breed, :age, :size, :gender, :temperament, :description, :location, :adoption_status, photo_urls: [])
    end

    def attach_photos
      params[:pet][:photo_urls].each do |signed_id|
        blob = ActiveStorage::Blob.find_signed(signed_id)
        @pet.photos.attach(blob)
      end
    end
  end
end

app/helpers/adopter/pets_helper.rb
module Adopter::PetsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/helpers/shelter/pets_helper.rb
module Shelter::PetsHelper
end

app/views/shelter_namespace/pets/_comments.html.erb
<div class="w-full flex flex-col justify-center items-center max-w-4xl mx-auto">
  <div class="w-full">
    <div class="w-full flex justify-center items-center">
      <div class="w-full bg-white p-6 rounded-lg shadow-lg">
        <div>
          <%= form_with(model: [@pet, @pet_comment], url: shelter_namespace_pet_pet_comments_path(@pet), id: "new_comment", local: true) do |form| %>
            <div class="flex items-center w-full">
              <%= form.text_area :comment_text, placeholder: "Add a comment", class: "w-full flex-1 rounded-3xl p-4 mr-2 h-16", id: "comment_text_area" %>
              <button type="submit" class="flex items-center justify-center bg-blue-500 text-white rounded-3xl p-5 transition duration-500 ease-in-out hover:bg-blue-700 disabled:opacity-50" id="submit_button" disabled>
                <i class="fa-solid fa-arrow-right-to-bracket text-xl"></i>
              </button>
            </div>
          <% end %>
        </div>

        <div class="mt-6">
          <% @pet.pet_comments.each do |pet_comment| %>
            <div class="flex items-start mb-4">
              <div class="relative flex items-center justify-center w-14 h-14 rounded-full bg-violet-600 text-white mr-4">
                <span><%= pet_comment.user.username[0].upcase %></span>
                <div class="absolute bottom-0 right-0 w-4 h-4 bg-teal-400 border-2 border-white rounded-full"></div>
              </div>
              <div class="w-full">
                <div class="w-full bg-gray-200 p-3 pl-4 rounded-2xl">
                  <p><strong><%= display_name(pet_comment.user) %></strong></p>
                  <p><%= pet_comment.comment_text %></p>
                </div>
                <p class="pl-4 pt-1 text-gray-500 text-md"><%= time_ago(pet_comment.created_at) %></p>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shelter_namespace/pets/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Shelter::Pets#create</h1>
  <p>Find me in app/views/shelter/pets/create.html.erb</p>
</div>

app/views/shelter_namespace/pets/delete_photo.js.erb
document.addEventListener("DOMContentLoaded", function() {
  var photoContainer = document.querySelector("div[data-photo-id='<%= params[:photo_id] %>']");
  if (photoContainer) {
    photoContainer.remove();
  }

  var flashNotice = document.createElement('div');
  flashNotice.className = 'alert alert-notice';
  flashNotice.innerText = '<%= j flash[:notice] %>';
  document.body.appendChild(flashNotice);
});

app/views/shelter_namespace/pets/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Shelter::Pets#destroy</h1>
  <p>Find me in app/views/shelter/pets/destroy.html.erb</p>
</div>

app/views/shelter_namespace/pets/index.html.erb
<div class="relative bg-white">
  <h1 class="font-bold text-4xl mb-4 bg-green text-white px-6 py-8 text-center header-radius">Pets</h1>
  <%= image_tag('cute_cat.png', class: "absolute -bottom-20 left-2 w-16 md:w-60 z-10") %>
  <%= image_tag('cute_dog.png', class: "absolute bottom-0 right-2 w-16 md:w-64 z-10") %>
</div>

<% if @pets.any? %>
  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 p-6">
    <% @pets.each do |pet| %>
      <div class="bg-white rounded-lg shadow-md p-6">
        <% if pet.photos.attached? %>
          <div class="overflow-hidden rounded-t-lg">
            <%= image_tag url_for(pet.photos.first), class: "w-full h-48 object-cover" %>
          </div>
          <% else %>
            <div class="overflow-hidden rounded-t-lg flex items-center justify-center bg-gray-200 h-48">
              <div class="w-full h-48 bg-gray-200 flex items-center justify-center rounded-lg mb-4">
                <%= image_tag 'paw.png', class: 'w-24 h-24' %>
              </div>
            </div>
        <% end %>
        <div class="mt-4">
          <h2 class="text-xl font-bold mb-2"><%= link_to pet.name, shelter_namespace_pet_path(pet), class: 'text-blue-500 hover:text-blue-700' %></h2>
          <p class="text-gray-700"><strong>Species:</strong> <%= pet.species.capitalize %></p>
          <p class="text-gray-700"><strong>Breed:</strong> <%= pet.breed.capitalize %></p>
          <p class="text-gray-700"><strong>Age:</strong> <%= pet.age %></p>
          <p class="text-gray-700"><strong>Size:</strong> <%= pet.size %></p>
          <p class="text-gray-700"><strong>Gender:</strong> <%= pet.gender.capitalize %></p>
          <p class="text-gray-700"><strong>Adoption Status:</strong> <%= pet.adoption_status.capitalize %></p>
          <div class="mt-4 flex justify-between">
            <%= link_to edit_shelter_namespace_pet_path(pet), class: 'text-yellow-500 hover:text-yellow-700 flex items-center' do %>
              <i class="fa-solid fa-pencil-alt mr-2"></i> Edit
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p class="text-red-500 text-center">No pets found.</p>
<% end %>

<div class="flex justify-center">
  <%= link_to 'New Pet', new_shelter_namespace_pet_path, class: 'mt-4 bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
</div>

app/views/shelter_namespace/pets/show.html.erb
<div class="relative bg-white">
  <h1 class="font-bold text-4xl mb-4 bg-green text-white px-6 py-8 text-center header-radius"><%= @pet.name %></h1>
  <%= image_tag('cute_cat.png', class: "absolute -bottom-20 left-2 w-16 md:w-60 z-10") %>
  <%= image_tag('cute_dog.png', class: "absolute bottom-0 right-2 w-16 md:w-64 z-10") %>
</div>

<div class="flex flex-col md:flex-row items-center md:items-start bg-white shadow-lg rounded-lg p-8 w-full max-w-4xl mx-auto">
  <div class="md:w-1/3 mb-4 md:mb-0 md:mr-8">
    <% if @pet.photos.attached? %>
      <div class="overflow-x-auto whitespace-nowrap">
        <% @pet.photos.each do |photo| %>
          <div class="inline-block relative mr-2" data-photo-id="<%= photo.id %>">
            <%= image_tag url_for(photo) + "?t=" + @pet.updated_at.to_i.to_s, class: "w-full h-auto rounded-full shadow-md mb-2" %>
            <%= button_to '×', delete_photo_shelter_namespace_pet_path(@pet, photo_id: photo.id), method: :delete, remote: true, turbo: true, data: { confirm: "Are you sure?" }, class: "absolute top-0 right-0 bg-red-500 text-white rounded-full px-2 py-1 text-xs font-bold" %>
          </div>
        <% end %>
      </div>
    <% else %>
      <div class="overflow-hidden rounded-t-lg flex items-center justify-center bg-gray-200 h-48">
          <div class="w-full h-48 bg-gray-200 flex items-center justify-center rounded-lg mb-4">
            <%= image_tag 'paw.png', class: 'w-24 h-24' %>
          </div>
      </div>
    <% end %>
  </div>

  <div class="md:w-2/3">
    <p class="mb-2 text-gray-700"><strong>Species:</strong> <%= @pet.species.capitalize %></p>
    <p class="mb-2 text-gray-700"><strong>Breed:</strong> <%= @pet.breed.capitalize %></p>
    <p class="mb-2 text-gray-700"><strong>Age:</strong> <%= @pet.age %></p>
    <p class="mb-2 text-gray-700"><strong>Size:</strong> <%= @pet.size %></p>
    <p class="mb-2 text-gray-700"><strong>Gender:</strong> <%= @pet.gender.capitalize %></p>
    <p class="mb-2 text-gray-700"><strong>Temperament:</strong> <%= @pet.temperament.capitalize %></p>
    <p class="mb-2 text-gray-700"><strong>Description:</strong> <%= @pet.description.capitalize %></p>
    <p class="mb-2 text-gray-700"><strong>Location:</strong> <%= @pet.location.capitalize %></p>
    <p class="mb-2 text-gray-700"><strong>Adoption Status:</strong> <%= @pet.adoption_status.capitalize %></p>

    <div class="flex justify-between mt-4">
      <%= link_to 'Edit Pet', edit_shelter_namespace_pet_path(@pet), class: 'bg-teal-500 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
      <%= link_to 'Back to Pets', shelter_namespace_pets_path, class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline' %>
    </div>
  </div>
</div>

<div class="w-full flex justify-center items-center mt-4">
  <%= render partial: 'shelter_namespace/pets/comments', locals: { pet: @pet, pet_comments: @pet_comments } %>
</div>

<script>
  function enableSubmitButton() {
    const commentTextArea = document.getElementById("comment_text_area");
    const submitButton = document.getElementById("submit_button");

    if (commentTextArea && submitButton) {
      commentTextArea.addEventListener("input", function() {
        if (commentTextArea.value.trim() === "") {
          submitButton.disabled = true;
        } else {
          submitButton.disabled = false;
        }
      });
    }
  }

  document.addEventListener("DOMContentLoaded", enableSubmitButton);
  document.addEventListener("turbo:load", enableSubmitButton);
</script>

app/views/shelter_namespace/pets/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Shelter::Pets#update</h1>
  <p>Find me in app/views/shelter/pets/update.html.erb</p>
</div>

app/views/shelter_namespace/pets/update_status.html.erb
<div>
  <h1 class="font-bold text-4xl">Shelter::Pets#update_status</h1>
  <p>Find me in app/views/shelter/pets/update_status.html.erb</p>
</div>