config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :list_of_users, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "landing_page#index"
  # admin
  namespace :admin do
    get 'dashboard/index'
    root to: 'dashboard#index', as: 'dashboard'
    # users
    resources :users do
      member do
        patch :approve
        delete :deny
        # get 'chat'
      end
      # invite_user
      collection do
        get :invite_user_form
        post :invite_user
      end
    end
    resources :adoption_applications, only: [:index, :show]
    resources :adopters, only: [:edit, :update]
    resources :shelters, only: [:edit, :update]
    resources :pets, only: [:show]
  end

  devise_scope :user do
    get 'invite_user/:invitation_token', to: 'users/registrations#new_invited_user', as: 'new_invitation'
    post 'create_user', to: 'users/registrations#create_invited_user'
  end

  namespace :adopter do
    get 'dashboard', to: 'dashboard#index'
    resources :favorites, only: [:index, :create, :destroy]
    resources :pets, only: [:index, :show, :create] do
      resources :comments, only: [:create, :destroy]
    end
    resources :adoption_applications
  end

  namespace :shelter_namespace, path: 'shelter' do
    get 'dashboard', to: 'dashboard#index'
    resources :pets do
      member do
        patch :update_status
        delete :delete_photo  # Adding this line for the delete photo action
      end
      collection do
        post :uploads  # Adding this line for the uploads action in the create new pet view for shelters
      end
      resources :pet_comments, only: [:create]
    end
    resources :adoption_applications, only: [:index, :show, :edit, :update] do
      member do
        patch :approve
        patch :deny
        patch :pending
      end
    end
    resources :adopters, only: [:show]
    resources :chats, only: [:index, :show, :create]
  end

  namespace :sendbird do
    post '/create_group_channel_to_sendbird', to: 'sendbird#create_group_channel_to_sendbird'
    get 'list_users', to: 'sendbird#list_users'
    post 'send_message_to_sendbird', to: 'sendbird#send_message_to_sendbird'
    get 'fetch_messages_from_sendbird', to: 'sendbird#fetch_messages_from_sendbird'
  end

  # resources :list_of_users, only: [:index]
end

app/models/adopter.rb
class Adopter < ApplicationRecord
  belongs_to :user
  has_many :favorites
  has_many :adoption_applications

  validates :first_name, presence: true
  validates :last_name, presence: true

  def full_name
    "#{first_name} #{last_name}"
    end
end

app/models/pet.rb
class Pet < ApplicationRecord
  geocoded_by :location
  after_validation :geocode

  enum adoption_status: { available: 0, pending: 1, adopted: 2 }

  belongs_to :shelter
  has_many :favorites
  has_many :favorited_by_users, through: :favorites, source: :use
  has_many :adoption_applications
  has_many :pet_comments

  validates :name, presence: true
  validates :species, presence: true
  validates :breed, presence: true

  has_many_attached :photos

  scope :filter_by_species, ->(species) { where(species: species) if species.present? }
  scope :filter_by_age, ->(age) { where(age: age) if age.present? }
  scope :filter_by_gender, ->(gender) { where(gender: gender) if gender.present? }
  scope :filter_by_temperament, ->(temperament) { where(temperament: temperament) if temperament.present? }
  scope :filter_by_location, ->(location, distance, unit) {
    if location.present?
      near(location, distance || 15, units: unit || :mi)
    else
      where.not(adoption_status: 'adopted')
    end
  }
  scope :species_counts, -> { group(:species).count }
  scope :age_counts, -> { group(:age).count }
  scope :gender_counts, -> { group(:gender).count }
  scope :temperament_counts, -> { group(:temperament).count }
end

app/controllers/admin/adopters_controller.rb
class Admin::AdoptersController < Admin::BaseController
    before_action :set_adopter, only: [:edit, :update]
  
    def edit
    end
  
    def update
      if @adopter.update(adopter_params)
        redirect_to admin_user_path(@adopter.user), notice: 'Adopter details were successfully updated.'
      else
        render :edit
      end
    end
  
    private
  
    def set_adopter
      @adopter = Adopter.find(params[:id])
    end
  
    def adopter_params
      params.require(:adopter).permit(:first_name, :last_name, :preference)
    end
  end
  

app/controllers/admin/pets_controller.rb
module Admin
    class PetsController < BaseController
      def show
        @pet = Pet.find(params[:id])
      end
    end
  end
  

app/controllers/adopter/adoption_applications_controller.rb
class Adopter::AdoptionApplicationsController < Adopter::BaseController
  before_action :set_adoption_application, only: [:show, :destroy]

  def index
    @adoption_applications = current_user.adopter.adoption_applications
  end

  def show
    # before_action set_adoption_application heree
  end

  def new
    @adoption_application = AdoptionApplication.new
  end

  def create
    adopter = Adopter.find_by(user_id: current_user.id)
    @adoption_application = AdoptionApplication.new(adoption_application_params)
    @adoption_application.application_date = Date.today
    @adoption_application.adopter_id = adopter.id
  
    existing_application = AdoptionApplication.find_by(adopter_id: adopter.id, pet_id: @adoption_application.pet_id)
  
    if existing_application
      redirect_to adopter_adoption_applications_path, alert: 'You have an existing adoption application for this pet.'
    else
      if @adoption_application.save
        update_pet_status(@adoption_application.pet) # Update pet status after saving
        redirect_to adopter_adoption_applications_path, notice: 'Adoption application was successfully created.'
      else
        render :new
      end
    end
  end
  

  def destroy
    # @adoption_application is set in before_action
    @adoption_application.destroy
    update_pet_status(@adoption_application.pet) # Update pet status after saving
    redirect_to adopter_adoption_applications_path, notice: "Application has been withdrawn."
  end

  private

  def set_adoption_application
    @adoption_application = AdoptionApplication.find(params[:id])
  end

  def adoption_application_params
    params.require(:adoption_application).permit(:adopter_id, :pet_id, :status, :application_date)
  end

  def update_pet_status(pet) # Update pet status after saving
    if pet.adoption_applications.approved.exists?
      pet.update!(adoption_status: :adopted)
    elsif pet.adoption_applications.submitted.exists?
      pet.update!(adoption_status: :pending)
    else
      pet.update!(adoption_status: :available) 
    end
  end
end

app/controllers/adopter/base_controller.rb
class Adopter::BaseController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_adopter

  private

  def ensure_adopter
    unless current_user&.adopter?
      raise User::NotAuthorized, 'Access denied.'
    end
  end

end

app/controllers/adopter/comments_controller.rb
class Adopter::CommentsController < Adopter::BaseController
  before_action :set_pet

  def create
    @pet_comment = @pet.pet_comments.build(comment_params)
    @pet_comment.user = current_user

    if @pet_comment.save
      flash[:notice] = "Comment was successfully added."
      redirect_to adopter_pet_path(@pet)
    else
      flash[:alert] = "Unable to add comment"
      render 'adopter/pets/show'
    end
  end
  
  private

  def set_pet
    @pet = Pet.find(params[:pet_id])
  end

  def comment_params
    params.require(:pet_comment).permit(:comment_text)
  end

end

app/controllers/adopter/dashboard_controller.rb
class Adopter::DashboardController < Adopter::BaseController
  
  def index
  end
end

app/controllers/adopter/favorites_controller.rb
class Adopter::FavoritesController < Adopter::BaseController
  
  def index
    @favorites = current_user.favorites.includes(:pet)
  end

  def create
    pet = Pet.find(params[:pet_id])
    current_user.favorites.create(pet: pet)
    redirect_to adopter_pets_path, notice: "Added to favorites"
  end

  def destroy
    favorite = current_user.favorites.find_by(pet_id: params[:pet_id])
    if favorite
      favorite.destroy
      notice_message = "Removed from favorites"
    else
      notice_message = "Favorite not found"
    end
    redirect_path = params[:redirect_to] == 'favorites' ? adopter_favorites_path : adopter_pets_path
    redirect_to redirect_path, notice: notice_message
  end
  
end

app/controllers/adopter/pets_controller.rb
class Adopter::PetsController < Adopter::BaseController

  def index
    @pets = Pet.filter_by_species(params[:species])
                .filter_by_age(params[:age])
                .filter_by_gender(params[:gender])
                .filter_by_temperament(params[:temperament])
                .filter_by_location(params[:location], params[:distance], params[:unit])
    @species_counts = Pet.species_counts
    @age_counts = Pet.age_counts
    @gender_counts = Pet.gender_counts
    @temperament_counts = Pet.temperament_counts
  end

  def show
    @pet = Pet.find(params[:id])
    @pet_comment = PetComment.new
  end

  def create
    pet = Pet.find(params[:pet_id])
    if current_user.favorites.include?(pet)
      current_user.favorites.delete(pet)
      flash[:notice] = "Removed from favorites"
    else
      current_user.favorites << pet
      flash[:notice] = "Added to favorites"
    end
    redirect_to pets_path
  end

end

app/controllers/shelter/pets_controller.rb
module Shelter
  class PetsController < BaseController
    before_action :set_pet, only: [:show, :edit, :update, :destroy, :update_status]

  def index
    @pets = current_user.shelter.pets

    if params[:location].present?
      distance = params[:distance].present? ? params[:distance].to_f : 15
      unit = params[:unit] == 'km' ? :km : :mi  # allows user to select if km or miles
      @pets = @pets.near(params[:location], distance, units: unit)
    end
  end


  def show
    @pet_comment = PetComment.new
  end



  def create
    @pet = current_user.shelter.pets.build(pet_params)
    if @pet.save
      flash[:notice] = "Pet added successfully"
      redirect_to shelter_pets_path
    else
      render :new
    end
  end



  def edit
  end

  def update
    if @pet.update(pet_params)
      flash[:notice] = "Pet updated successfully"
      redirect_to shelter_pet_path(@pet)
    else
      render :edit
    end
  end


  def destroy
    @pet.destroy
    flash[:notice] = "Pet removed successfully"
    redirect_to shelter_pets_path
  end

  def update_status
    if @pet.update(adoption_status: params[:adoption_status])
      flash[:notice] = "Pet status updated successfully"
    else
      flash[:alert] = "Unable to update status"
    end
    redirect_to shelter_pet_path(@pet)
  end

  def update_status
  end

  private

  def set_pet
    @pet = Pet.find(params[:id])
  end

  def pet_params
    params.require(:pet).permit(:name, :species, :breed, :age, :size, :gender, :temperament, :description, :photo_url, :location, :adoption_status)
   end
  end
end

app/controllers/shelter_namespace/adopters_controller.rb
module ShelterNamespace
  class AdoptersController < BaseController
      def show
          @adopter = Adopter.find(params[:id])
        end
      end
  end

app/controllers/shelter_namespace/pets_controller.rb
module ShelterNamespace
  class PetsController < BaseController
    before_action :set_pet, only: [:show, :edit, :update, :destroy, :update_status, :delete_photo]

    def index
      @pets = current_user.shelter.pets

      if params[:location].present?
        distance = params[:distance].present? ? params[:distance].to_f : 15
        unit = params[:unit] == 'km' ? :km : :mi  # allows user to select if km or miles
        @pets = @pets.near(params[:location], distance, units: unit)
      end
    end

    def show
      @pet_comments = @pet.pet_comments.includes(:user)
      @pet_comment = PetComment.new
    end

    def new
      @pet = Pet.new
    end

    def create
      @pet = current_user.shelter.pets.build(pet_params.except(:photo_urls))
      if @pet.save
        attach_photos if params[:pet][:photo_urls].present?
        flash[:notice] = "Pet added successfully"
        redirect_to shelter_namespace_pets_path
      else
        render :new
      end
    end  

    def edit
    end

    def update
      if @pet.update(pet_params.except(:photo_urls))
        attach_photos if params[:pet][:photo_urls].present?
        flash[:notice] = "Pet updated successfully"
        redirect_to shelter_namespace_pet_path(@pet)
      else
        render :edit
      end
    end

    def destroy
      @pet.destroy
      flash[:notice] = "Pet removed successfully"
      redirect_to shelter_namespace_pets_path
    end

    def update_status
      if @pet.update(adoption_status: params[:adoption_status])
        flash[:notice] = "Pet status updated successfully"
      else
        flash[:alert] = "Unable to update status"
      end
      redirect_to shelter_namespace_pet_path(@pet)
    end

    def uploads
      uploaded_file = params[:file]
      blob = ActiveStorage::Blob.create_and_upload!(
        io: uploaded_file,
        filename: uploaded_file.original_filename,
        content_type: uploaded_file.content_type
      )
      render json: { file_url: blob.signed_id }
    end

    def delete_photo
      photo = @pet.photos.find(params[:photo_id])
      photo.purge
      flash.now[:notice] = "Photo deleted successfully"
      
      respond_to do |format|
        format.html { redirect_to shelter_namespace_pet_path(@pet) }
        format.js
      end
    end  

    private

    def set_pet
      @pet = Pet.find(params[:id])
    end

    def pet_params
      params.require(:pet).permit(:name, :species, :breed, :age, :size, :gender, :temperament, :description, :location, :adoption_status, photo_urls: [])
    end

    def attach_photos
      params[:pet][:photo_urls].each do |signed_id|
        blob = ActiveStorage::Blob.find_signed(signed_id)
        @pet.photos.attach(blob)
      end
    end
  end
end

app/helpers/adopter/adoptions_helper.rb
module Adopter::AdoptionsHelper
end

app/helpers/adopter/base_helper.rb
module Adopter::BaseHelper
end

app/helpers/adopter/comments_helper.rb
module Adopter::CommentsHelper
end

app/helpers/adopter/dashboard_helper.rb
module Adopter::DashboardHelper
end

app/helpers/adopter/favorites_helper.rb
module Adopter::FavoritesHelper
end

app/helpers/adopter/pets_helper.rb
module Adopter::PetsHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/adopter/pets/_comments.html.erb
<div class="w-full flex justify-end items-center pl-5">
  <div class="w-3/4 bg-white p-6 rounded-3xl shadow-lg">
    <div>
      <%= form_with(model: [@pet, @pet_comment], url: adopter_pet_comments_path(@pet), id: "new_comment", local: true) do |form| %>
        <div class="flex items-center w-full">
          <%= form.text_area :comment_text, placeholder: "Add a comment", class: "w-full flex-1 rounded-3xl p-4 mr-2 h-16" %>
          <button type="submit" class="flex items-center justify-center bg-blue-500 text-white rounded-3xl p-5 hover:bg-blue-700">
            <i class="fa-solid fa-arrow-right-to-bracket text-xl"></i>
          </button>
        </div>
      <% end %>
    </div>

    <div class="mt-6">
      <% @pet.pet_comments.each do |pet_comment| %>
        <%= render partial: "adopter/comments/comment", locals: { pet_comment: pet_comment } %>
      <% end %>
    </div>
  </div>
</div>

app/views/adopter/pets/index.html.erb
<div>
  <div class=" relative bg-white">
    <h1 class="font-bold text-4xl mb-4 bg-green text-white px-6 py-8 text-center header-radius">Our Pets Looking For a New Home</h1>
    <%= image_tag('cute_cat.png', class: "absolute -bottom-20 left-2 w-16 md:w-60 z-10") %>
    <%= image_tag('cute_dog.png', class: "absolute bottom-0 right-2 w-16 md:w-64 z-10") %>
  </div>

  <div class="flex justify-start items-start bg-gray-100 rounded">

    <div class="flex flex-col justify-center items-center w-1/5 p-2 mt-2">
      <div class="flex flex-col justify-center ml-2">
        <h2 class="font-bold text-2xl my-4 ml-2">Filter</h2>
        <%= form_with url: adopter_pets_path, method: :get, local: true do |form| %>
          <div class="mb-4">
            <%= form.text_field :location, placeholder: "Location (Enter City)", class: "w-full rounded-2xl p-3 border-2" %>
          </div>
          <div class="mb-6">
            <%= form.label :distance, "Distance" %>
            <div class="flex">
              <%= form.number_field :distance, value: 15, class: "w-full rounded-2xl p-3 border-2" %>
              <%= form.select :unit, options_for_select([['Miles', 'mi'], ['Kilometers', 'km']], 'mi'), {}, { class: "ml-1 w-full rounded-2xl p-3 border-2" } %>
            </div>
          </div>
          <div class="mb-4">
            <% options = @species_counts.map { |species, count| ["#{species} (#{count})", species] } %>
            <% options.unshift(["Select Species (optional)", "", disabled: true, selected: true]) %>
            <%= form.select :species, options_for_select(options), { include_blank: true }, { id: 'species_select', class: 'form-control w-full rounded-2xl p-3 border-2' } %>
          </div>
          <div class="mb-4">
            <% options = @age_counts.map { |age, count| ["#{age} (#{count})", age] } %>
            <% options.unshift(["Select Age (optional)", "", disabled: true, selected: true]) %>
            <%= form.select :age, options_for_select(options), { include_blank: true }, { id: 'age_select', class: 'form-control w-full rounded-2xl p-3 border-2' } %>
          </div>

          <div class="mb-4">
            <% options = @gender_counts.map { |gender, count| ["#{gender} (#{count})", gender] } %>
            <% options.unshift(["Select Gender (optional)", "", disabled: true, selected: true]) %>
            <%= form.select :gender, options_for_select(options), { include_blank: true }, { id: 'gender_select', class: 'form-control w-full rounded-2xl p-3 border-2' } %>
          </div>

          <div class="mb-4">
            <% options = @temperament_counts.map { |temperament, count| ["#{temperament} (#{count})", temperament] } %>
            <% options.unshift(["Select Temperament (optional)", "", disabled: true, selected: true]) %>
            <%= form.select :temperament, options_for_select(options), { include_blank: true }, { id: 'temperament_select', class: 'form-control w-full rounded-2xl p-3 border-2' } %>
          </div>
          <div class="mb-4">
            <%= form.submit "Search", class: 'bg-green w-full p-3.5 rounded-2xl text-vanilla cursor-pointer text-lg hover:bg-green-2 transition duration-500 ease-in-out' %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="w-4/5 p-6">
      <% if @pets.present? %>
        <ul class="flex flex-wrap justify-center items-center m-auto p-6 rounded-3xl shadow-xl bg-white">
          <% @pets.each do |pet| %>
            <li class="w-1/4 m-3 shadow rounded-2xl p-4 mx-8 bg-gray-100 text-center">
              <div class="relative w-full h-56 border mb-2 rounded-xl">
                <% if pet.photos.any? %>
                    <%= image_tag url_for(pet.photos.first), class: 'w-full h-full object-cover rounded-lg' %>
                <% else %>
                  <% if pet.species == 'Cat' %>
                    <%= image_tag('dp_cat.png', class: 'w-full h-full object-cover') %>
                  <% elsif pet.species == 'Dog' %>
                    <%= image_tag('dp_dog.png', class: 'w-full h-full object-cover') %>
                  <% else %>
                    <%= image_tag('paw.png', class: 'w-full h-full object-cover') %>
                  <% end %>
                <% end %>

                <div class="absolute bottom-2 right-2 bg-slate-200 py-2 px-3 rounded-full hover:bg-slate-300 transition duration-500 ease-in-out">
                  <% if current_user.favorites.exists?(pet_id: pet.id) %>
                    <%= form_with(url: adopter_favorite_path(id: pet.id), method: :delete, local: true) do %>
                      <%= hidden_field_tag :pet_id, pet.id %>
                      <%= button_tag type: 'submit', class: 'btn text-xl' do %>
                        <i class="fa-solid fa-heart" style="color: crimson;"></i>
                      <% end %>
                    <% end %>
                  <% else %>
                    <%= form_with(url: adopter_favorites_path, method: :post, local: true) do %>
                      <%= hidden_field_tag :pet_id, pet.id %>
                      <%= hidden_field_tag :redirect_to, 'pets' %>
                      <%= button_tag type: 'submit', class: 'btn text-xl' do %>
                        <i class="fa-regular fa-heart" style="color: crimson;"></i>
                      <% end %>
                    <% end %>
                  <% end %>
                </div>

                <div class="absolute bottom-2 left-2 bg-slate-200 py-2 px-3.5 rounded-full hover:bg-slate-300 hover:text-black transition duration-500 ease-in-out">
                  <button class="adopt-button" data-pet-id="<%= pet.id %>" data-pet-name="<%= pet.name %>">
                    <i class="fa-solid fa-hand-holding-heart mr-1" style="color: teal;"></i>
                    <span class="text-blue-700">Adopt</span>
                  </button>
                </div>
              </div>

              <p class="text-xl"><strong><%= link_to pet.name.capitalize, adopter_pet_path(pet) %></strong> - <%= pet.gender.capitalize %></p>
              <p><%= pet.location.capitalize %></p>
              <p><%= pet.species.capitalize %> - <%= pet.breed.capitalize %></p>
              <p><%= pet.age %> years old</p>

              <p class="mt-4">
                <%= link_to adopter_pet_path(pet), class: "text-blue-500 hover:text-blue-700" do %>
                  <i class="fas fa-comments mr-1"></i>
                  Comments <span class="text-sm text-gray-600 border px-1.5 rounded"><%= pet.pet_comments.size %></span>
                <% end %>
              </p>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p class="text-center text-xl">No pets found matching the selected criteria.</p>
      <% end %>
    </div>

    <div id="confirmationModal" class="fixed inset-0 z-50 overflow-auto flex items-center justify-center hidden">
      <div class="modal-overlay absolute w-full h-full bg-gray-900 opacity-50"></div>
      <div class="modal-container bg-white w-11/12 md:max-w-md mx-auto rounded-2xl shadow-lg z-50 overflow-y-auto">
        <div class="modal-content p-6 text-left">
          <div class="flex justify-start items-start pb-8">
            <p class="text-xl">Please confirm if you want to submit an adoption application for <span id="petName" class="font-bold"></span>.<br/>
            <span class="text-sm text-green-2">Note: You will be redirected to the application page if you click 'Yes'.</span>
            </p>
            <button id="closeModal" class="modal-close cursor-pointer z-50">X</button>
          </div>
          <div class="flex justify-end">
            <button id="confirmAdoption" class="px-4 py-2 bg-green text-white rounded hover:bg-green-2 transition duration-500 ease-in-out">Yes</button>
            <button id="cancelAdoption" class="px-4 py-2 bg-gray-300 text-gray-700 rounded hover:bg-gray-400 ml-4 transition duration-500 ease-in-out">Cancel</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  var modal = document.getElementById('confirmationModal');
  var closeModalBtn = document.getElementById('closeModal');
  var confirmAdoptionBtn = document.getElementById('confirmAdoption');
  var cancelAdoptionBtn = document.getElementById('cancelAdoption');
  function openModal(petName) {
    document.getElementById("petName").textContent = petName;
    modal.classList.remove('hidden');
    modal.classList.add('flex');
  }
  function closeModal() {
    modal.classList.add('hidden');
  }
  confirmAdoptionBtn.addEventListener('click', function() {
    var newAdoptionPath = "<%= j(new_adopter_adoption_application_path) %>"; 
    window.location.href = newAdoptionPath; 
  });
  cancelAdoptionBtn.addEventListener('click', function() {
    closeModal();
  });
  closeModalBtn.addEventListener('click', function() {
    closeModal();
  });
  document.querySelectorAll('.adopt-button').forEach(function(button) {
    button.addEventListener('click', function() {
      var petId = this.getAttribute('data-pet-id'); 
      var petName = this.getAttribute('data-pet-name'); 
      openModal(petName, petId);
    });
  });

</script>