config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :list_of_users, only: [:index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "landing_page#index"
  # admin
  namespace :admin do
    get 'dashboard/index'
    root to: 'dashboard#index', as: 'dashboard'
    # users
    resources :users do
      member do
        patch :approve
        delete :deny
        # get 'chat'
      end
      # invite_user
      collection do
        get :invite_user_form
        post :invite_user
      end
    end
    resources :adoption_applications, only: [:index, :show]
    resources :adopters, only: [:edit, :update]
    resources :shelters, only: [:edit, :update]
    resources :pets, only: [:show]
  end

  devise_scope :user do
    get 'invite_user/:invitation_token', to: 'users/registrations#new_invited_user', as: 'new_invitation'
    post 'create_user', to: 'users/registrations#create_invited_user'
  end

  namespace :adopter do
    get 'dashboard', to: 'dashboard#index'
    resources :favorites, only: [:index, :create, :destroy]
    resources :pets, only: [:index, :show, :create] do
      resources :comments, only: [:create, :destroy]
    end
    resources :adoption_applications
  end

  namespace :shelter_namespace, path: 'shelter' do
    get 'dashboard', to: 'dashboard#index'
    resources :pets do
      member do
        patch :update_status
        delete :delete_photo  # Adding this line for the delete photo action
      end
      collection do
        post :uploads  # Adding this line for the uploads action in the create new pet view for shelters
      end
      resources :pet_comments, only: [:create]
    end
    resources :adoption_applications, only: [:index, :show, :edit, :update] do
      member do
        patch :approve
        patch :deny
        patch :pending
      end
    end
    resources :adopters, only: [:show]
    resources :chats, only: [:index, :show, :create]
  end

  namespace :sendbird do
    post '/create_group_channel_to_sendbird', to: 'sendbird#create_group_channel_to_sendbird'
    get 'list_users', to: 'sendbird#list_users'
    post 'send_message_to_sendbird', to: 'sendbird#send_message_to_sendbird'
    get 'fetch_messages_from_sendbird', to: 'sendbird#fetch_messages_from_sendbird'
  end

  # resources :list_of_users, only: [:index]
end

app/views/shared/_chat_interface.html.erb
<div id="chat-container" class="hidden fixed bottom-0 right-0 w-96 bg-white shadow-lg border border-gray-300 rounded-lg z-10">
  <div class="flex items-center justify-between bg-orange-500 text-white p-3 border-b border-gray-300">
    <span id="chat-username" class="font-semibold text-white-700"></span>
    <div class="flex items-center space-x-2">
      <button id="minimize-chat" class="text-white-500 hover:text-gray-700">-</button>
      <button id="close-chat" class="text-white-500 hover:text-gray-700">&times;</button>
    </div>
  </div>

  <div id="chat-messages-container" class="p-3 h-64 overflow-y-scroll">
    <div id="chat-messages-sample" class="chat-messages"></div>
  </div>
  <div class="p-3 border-t border-gray-300">
    <input type="text" id="chat-input" class="w-full border border-gray-300 rounded-lg p-2" placeholder="Type a message...">
  </div>
</div>

app/views/shared/_list_of_users.html.erb
<div id="users-list" class="hidden h-full w-72 bg-persian-orange text-black flex-col justify-between p-4 rounded-3xl">
  <h2>Chats</h2>
  <input type="text" class="search-user h-8 w-50 pr-8 pl-5 rounded-xl z-0 focus:shadow focus:outline-none" placeholder="Search user">

  <div class="list-of-users h-64 overflow-y-auto mt-3">
    <% if @users.present? %>
      <ul>
        <% @users.each do |user| %>
          <% sendbird_user = @sendbird_users.find { |sendbird_user| sendbird_user[:user_id] == user.id.to_s } %>
          <% if sendbird_user %>
            <li class="flex items-center mt-2 py-2 px-4 border cursor-pointer shadow rounded-xl hover:border-2 hover:border-straw hover:bg-straw hover:text-black transition duration-300 ease-in-out
                        chat-link"
                        data-user-id="<%= user.id %>" 
                        data-username="<%= user.username %>">
              <!-- Check if the user is active and display a green circle -->
              <% if sendbird_user[:active_mode] == "activated" %>
                <div class="h-3 w-3 bg-green-500 rounded-full mr-2"></div>
              <% end %>
              <img src="<%= sendbird_user[:profile_url] %>" alt="<%= sendbird_user[:nickname] %>" class="h-8 w-8 rounded-full">
              <span class="px-2"><%= sendbird_user[:nickname] %></span>
            </li>
          <% end %>
        <% end %>
      </ul>
    <% else %>
      <p>No users found.</p>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="h-full w-72 bg-persian-orange text-black flex flex-col justify-between p-4 rounded-3xl">
  <ul class="space-y-2">
    <li class="mb-6 mt-2">
      <p class="flex items-center ml-2">
        <i class="fa-solid fa-circle-user fa-2xl fa-nav"></i>
        <span class="ml-3 block py-2 px-4 border shadow rounded-xl w-full text-center"><%= display_name(current_user) %></span>
      </p>
    </li>

    <!-- Admin-specific links -->
    <% if current_user.admin? %>
      <li class="mb-2">
        <%= link_to admin_dashboard_path, class: "flex items-center py-2 px-4 border shadow rounded-xl hover:border-2 hover:border-straw hover:bg-straw hover:text-black transition duration-300 ease-in-out" do %>
          <i class="fa-solid fa-feather mr-3.5"></i>
            Dashboard
        <% end %>
      </li>

      <li class="mb-2">
        <%= link_to admin_users_path, class: "flex items-center py-2 px-4 border shadow rounded-xl hover:border-2 hover:border-straw hover:bg-straw hover:text-black transition duration-300 ease-in-out" do %>
          <i class="fa-solid fa-users mr-3.5"></i>
            Manage Users
        <% end %>
      </li>

      <li class="mb-2">
        <%= link_to admin_adoption_applications_path, class: "flex items-center py-2 px-4 border shadow rounded-xl hover:border-2 hover:border-straw hover:bg-straw hover:text-black transition duration-300 ease-in-out" do %>
          <i class="fa-solid fa-paw mr-3.5"></i>
            Adoption Applications
        <% end %>
      </li>

      <li class="mb-2">
        <%= link_to invite_user_form_admin_users_path, class: "flex items-center py-2 px-4 border shadow rounded-xl hover:border-2 hover:border-straw hover:bg-straw hover:text-black transition duration-300 ease-in-out" do %>
          <i class="fa-solid fa-paper-plane mr-3.5"></i>
            Invite User
        <% end %>
      </li>

      <li class="mb-2">
        <button id="btn-chat" class="flex items-center w-full py-2 px-4 border shadow rounded-xl hover:border-2 hover:border-straw hover:bg-straw hover:text-black transition duration-300 ease-in-out">
          <i class="fa-solid fa-comments mr-3.5"></i>
          Chats
        </button>
      </li>

    <!-- Adopter-specific links -->
    <% elsif current_user.adopter? %>
      <li class="mb-2">
        <%= link_to adopter_dashboard_path, class: "flex items-center py-2 px-4 border shadow rounded-xl hover:border-2 hover:border-straw hover:bg-straw hover:text-black transition duration-300 ease-in-out" do %>
          <i class="fa-solid fa-feather mr-3"></i>
            Dashboard
        <% end %>
      </li>

      <li class="mb-2">
        <%= link_to adopter_pets_path, class: "flex items-center py-2 px-4 border shadow rounded-xl hover:border-2 hover:border-straw hover:bg-straw hover:text-black transition duration-300 ease-in-out" do %>
          <i class="fa-solid fa-paw mr-3"></i>
            All About Pets
        <% end %>
      </li>

      <li class="mb-2">
        <%= link_to adopter_favorites_path, class: "flex items-center py-2 px-4 border shadow rounded-xl hover:border-2 hover:border-straw hover:bg-straw hover:text-black transition duration-300 ease-in-out" do %>
          <i class="fa-solid fa-heart mr-3"></i>
            My Favorite Pets
        <% end %>
      </li>

      <li class="mb-2">
        <%= link_to adopter_adoption_applications_path, class: "flex items-center py-2 px-4 border shadow rounded-xl hover:border-2 hover:border-straw hover:bg-straw hover:text-black transition duration-300 ease-in-out" do %>
          <i class="fa-solid fa-hand-holding-heart mr-3"></i>
            Adoption Applications
        <% end %>
      </li>

      <li class="mb-2b w-full">
         <button id="btn-chat" class="flex items-center w-full py-2 px-4 border shadow rounded-xl hover:border-2 hover:border-straw hover:bg-straw hover:text-black transition duration-300 ease-in-out">
          <i class="fa-solid fa-comments mr-3.5"></i>
          Chats
        </button>
      </li>

    <!-- Shelter-specific links -->
  <% elsif current_user.shelter? %>
    <li class="mb-2">
      <%= link_to shelter_namespace_dashboard_path, class: "flex items-center py-2 px-4 border shadow rounded-xl hover:border-2 hover:border-straw hover:bg-straw hover:text-black transition duration-300 ease-in-out" do %>
        <i class="fa-solid fa-feather mr-3"></i>
          Dashboard
      <% end %>
    </li>

    <li class="mb-2">
      <%= link_to shelter_namespace_pets_path, class: "flex items-center py-2 px-4 border shadow rounded-xl hover:border-2 hover:border-straw hover:bg-straw hover:text-black transition duration-300 ease-in-out" do %>
        <i class="fa-solid fa-paw mr-3"></i>
          Manage Pets
      <% end %>
    </li>

    <li class="mb-2">
      <%= link_to shelter_namespace_adoption_applications_path, class: "flex items-center py-2 px-4 border shadow rounded-xl hover:border-2 hover:border-straw hover:bg-straw hover:text-black transition duration-300 ease-in-out" do %>
        <i class="fa-solid fa-hand-holding-heart mr-3"></i>
          Adoption Applications
      <% end %>
    </li>

    <li class="mb-2">
       <button id="btn-chat" class="flex items-center w-full py-2 px-4 border shadow rounded-xl hover:border-2 hover:border-straw hover:bg-straw hover:text-black transition duration-300 ease-in-out">
          <i class="fa-solid fa-comments mr-3.5"></i>
          Chats
        </button>
    </li>
  <% end %>

  <%# do not edit beyond this comment %>
  </ul>

  <div class="relative">
    <div class="relative -bottom-2 ml-4">
      <%= image_tag('blcat.png', class: 'w-full z-10')%>
    </div>
    <div class="mb-4">
      <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "w-full py-2 px-4 hover:text-green border border-black border-2 shadow rounded-2xl hover:border-2 hover:border-black hover:bg-vanilla transition duration-500 ease-in-out" %>
    </div>
  </div>
</nav>